### ISSUE TITLE
get 6D rotation representation from rotation matrix or quaternion

### ISSUE THREAD

**Issue by kaixin-bai** [papagina/RotationContinuity#3]
Thanks a lot for your work. I have a question, how to get 6D rotation representation from rotation matrix or quaternion?

**Comment by kaixin-bai** [comment]
just find (14)

**Comment by pgrady3** [comment]
To clarify a little further, equation 14 in the supplementary says take the first two columns from the 3x3 rotation matrix. So something along these lines

`def rot_to_6d(rot_matrix):
    return np.concatenate((rot_matrix[:, 0], rot_matrix[:, 1]))`
