### ISSUE TITLE
which loss is better?

### ISSUE THREAD

**Issue by pyni** [papagina/RotationContinuity#5]
Hi, I find there are three losses in your code:
loss_t,loss_rmat,loss_geodesic
so, which loss is a best metrics to evaluate two translations (or two matrices)?

**Comment by papagina** [comment]
Hi pyni, in the three experiments in our paper, they achieve very close results. But some people told me that they found using L2 loss on the rotation matrices outperforms the geodesic one.

**Comment by pyni** [comment]
I see, thanks.

**Comment by dorianhenning** [comment]
BLASPHEMY!
https://en.wikipedia.org/wiki/3D_rotation_group
